[options]
    colorscheme = "gruvbox"
    colorscheme_bg = "dark"
    enable_guicolors = true

    # Statusline options
    statusline_separator = "arrow"
    statusline_iseparator = "bar"
    enable_statusline_mode = true
    statusline_unicode_symbols = false
    statusline_left_sections = [
       'winnr',
       'major mode',
       'filename',
       'fileformat',
       'minor mode lighters',
       'version control info',
       'search status'
    ]
    statusline_right_sections = [
       'cursorpos',
       'percentage',
       'input method',
       'date',
       'time'
    ]
    buffer_index_type = 4

    # File tree stuff
    enable_tabline_filetype_icon = false
    filetree_direction = "left"

    # Enable vim compatible mode, avoid changing origin vim key bindings
    vimcompatible = true


[[layers]]
    name = "core"
    enable_smooth_scrolling = false


[[layers]]
    name = "autocomplete"
    enable = false


[[layers]]
  name = "core#statusline"


[[layers]]
  name = "incsearch"
